<#
.SYNOPSIS
	Both-culture localization coverage gate for the Phase 1 completed-art tranche.

.DESCRIPTION
	Selects every entry in 01-INVENTORY.json with phase == 1, artwork_complete ==
	true, a non-empty internal_name, and localization.blocked != true. For each
	selected entry it derives the class short name and requires that name to appear
	as a key (a line beginning with `ShortName:`) in one
	Sources/Everglow/Localization/en-US/Mods.Everglow.Items.*.hjson file and in one
	Sources/Everglow/Localization/zh-Hans/Mods.Everglow.Items.*.hjson file.

	Excluding localization.blocked entries is deliberate. An entry whose key could
	not be produced is recorded with localization.blocked: true plus a blocker, and
	this gate honors that recorded blocker instead of failing on the entry. Entries
	with phase != 1 (the class-less Phase 2 routing) are never selected.

	Default mode exits non-zero listing any selected entry missing a key in either
	culture. With -AllowMissing it prints the same missing set but exits 0, so the
	pre-exporter baseline can be captured without failing.

	Keys are generated by the in-game exporter; this script never writes an HJSON
	file and never creates a key.

	This script is deliberately 100% ASCII (PowerShell 5.1 reads a BOM-less script
	as the system ANSI code page); the inventory and HJSON files are read through
	[IO.File]::ReadAllText so UTF-8 content is honoured.

.PARAMETER AllowMissing
	Report the missing-key set but exit 0 instead of failing.
#>
[CmdletBinding()]
param(
	[switch]$AllowMissing
)

$ErrorActionPreference = 'Stop'
$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
$phaseDir = Split-Path -Parent $scriptDir
$repoRoot = (Resolve-Path (Join-Path $phaseDir '..\..\..')).Path
$jsonPath = Join-Path $phaseDir '01-INVENTORY.json'
$enDir = Join-Path $repoRoot 'Sources/Everglow/Localization/en-US'
$zhDir = Join-Path $repoRoot 'Sources/Everglow/Localization/zh-Hans'
$hjsonFilter = 'Mods.Everglow.Items.*.hjson'

if (-not (Test-Path -LiteralPath $jsonPath)) {
	Write-Output "FAIL: inventory JSON not found: $jsonPath"
	exit 2
}

$inv = [IO.File]::ReadAllText($jsonPath) | ConvertFrom-Json
$entries = @($inv.entries)

# Concatenate the item-category HJSON files once per culture.
function Read-CultureText([string]$dir) {
	if (-not (Test-Path -LiteralPath $dir)) { return $null }
	$files = @(Get-ChildItem -LiteralPath $dir -Filter $hjsonFilter -File)
	if ($files.Count -eq 0) { return $null }
	$parts = New-Object System.Collections.Generic.List[string]
	foreach ($f in $files) { $parts.Add([IO.File]::ReadAllText($f.FullName)) }
	return ($parts -join "`n")
}

$enText = Read-CultureText $enDir
$zhText = Read-CultureText $zhDir
if ($null -eq $enText) {
	Write-Output "FAIL: no en-US item HJSON files found under $enDir"
	exit 2
}
if ($null -eq $zhText) {
	Write-Output "FAIL: no zh-Hans item HJSON files found under $zhDir"
	exit 2
}

$selected = @($entries | Where-Object {
	([int]$_.phase -eq 1) -and
	([bool]$_.artwork_complete) -and
	(-not [string]::IsNullOrWhiteSpace([string]$_.internal_name)) -and
	(-not [bool]$_.localization.blocked)
})

if ($selected.Count -eq 0) {
	Write-Output 'FAIL: phase-1 completed-art localization selection is empty'
	exit 1
}

$missing = New-Object System.Collections.Generic.List[string]
foreach ($e in $selected) {
	$id = [string]$e.id
	$parts = ([string]$e.internal_name).Split('.')
	$shortName = $parts[$parts.Length - 1]
	if ([string]::IsNullOrWhiteSpace($shortName)) {
		$missing.Add("$id : internal_name has no class short name")
		continue
	}
	$pattern = '(?m)^\s*' + [regex]::Escape($shortName) + '\s*:'
	$enHas = [regex]::IsMatch($enText, $pattern)
	$zhHas = [regex]::IsMatch($zhText, $pattern)
	if (-not ($enHas -and $zhHas)) {
		$cultures = @()
		if (-not $enHas) { $cultures += 'en-US' }
		if (-not $zhHas) { $cultures += 'zh-Hans' }
		$missing.Add(("{0} : {1} missing in {2}" -f $id, $shortName, ($cultures -join ', ')))
	}
}

$covered = $selected.Count - $missing.Count

if ($missing.Count -gt 0) {
	Write-Output "MISSING($($missing.Count)) of $($selected.Count) selected ($covered covered):"
	$missing | Sort-Object | ForEach-Object { Write-Output "  - $_" }
	if (-not $AllowMissing) {
		Write-Output 'FAIL: Phase 1 completed-art entries lack a key in en-US and/or zh-Hans.'
		exit 1
	}
	Write-Output 'ALLOW-MISSING: baseline recorded; exits 0 by request.'
	exit 0
}

Write-Output "OK(0): localization covered = $covered (of $($selected.Count) selected)"
exit 0
